language: csharp
mono: none
dotnet: 2.2.207
dist: xenial
install:
 - dotnet restore
script:
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover shortid.Test/shortid.Test.csproj
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
 - ./tools/csmacnz.Coveralls --opencover -i ./dotenv.net.Test/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $CIRCLE_SHA1 --commitBranch $CIRCLE_BRANCH --commitAuthor "$CIRCLE_USERNAME" --jobId $CIRCLE_BUILD_NUM --serviceName "circleci" --useRelativePaths