language: csharp
mono: none
dotnet: 2.2.207
dist: xenial
install:
 - dotnet restore
script:
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover shortid.Test/shortid.Test.csproj
 - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
 - ./tools/csmacnz.Coveralls --opencover -i ./shortid.Test/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName "travis-ci" --useRelativePaths